name: 'Bru collection/request runner'
description: 'Executes Bru CLI against a collection or request.'
author: 'Max Bauer @krummbar'

branding:
  color: orange
  icon: check-circle

inputs:
  path:
    description: >-
      Path of the target bruno collection.
      Should point to the root directory of the collection.
      If not provided it uses the current working directory.
    required: false
    default: .
  filename:
    description: >-
      File or folder name of the requests to run.
      It is relative to the `path` input.
    required: false
  recursive:
    description: Indicate a recursive run
    required: false
    default: 'false'
  env:
    description: Select a collection environment
    required: false
    default: ''
  envVars:
    description: List of environment variables to set with the run
    required: false
    default: ''
  output:
    description: Output file containing test results
    required: false
  outputFormat:
    description: >-
      The output format of the test results.
      Possible values 'html|json|junit'
    required: false
    default: 'json'
  insecure:
    description: Allow insecure server connections
    required: false
    default: 'false'
  testsOnly:
    description: 'Only run requests that have a test'
    required: false
  bail:
    description: 'Stop execution after a failure of a request, test, or assertion'
    required: false

outputs:
  success:
    description: 'Indicates test run success status'

runs:
  using: docker
  image: Dockerfile
